services:
    mysql:
        image: mysql:latest
        container_name: mysql-container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ws
            MYSQL_USER: man
            MYSQL_PASSWORD: secretss
        volumes:
            - mysql-data:/var/lib/mysql
    memcached:
        image: "memcached:alpine"
        ports:
            - "${FORWARD_MEMCACHED_PORT:-11211}:11211"
        networks:
            - sail
    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    mysql-data:
